In [1]:
import numpy as np

`np.array`: create a NumPy array with hand-picked values.

In [4]:
one_dim_array = np.array([1, 2, 3])

two_dim_array = np.array([[1, 2], [3, 4], [5,6]])

print(two_dim_array)

[[1 2]
 [3 4]
 [5 6]]


`np.zeros`: create a array full of zeros.
`np.ones`: create a array full of ones.

In [8]:
zeros = np.zeros([3, 2])

ones = np.ones(3)

print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


`np.arange`: create a sequence os number that includes the lower bound but not the upper bound.

In [9]:
sequence = np.arange(2, 5)

print(sequence)

[2 3 4]


`np.random.randint`: generates random integers between a low and a high value.

In [12]:
random_int_between_50_and_100 = np.random.randint(low=50, high=101, size=6)

print(random_int_between_50_and_100)

[81 52 99 94 86 66]


`np.random.random`: create random floats between 0.0 and 1.0

In [16]:
random_floats_between_0_and_1 = np.random.random(size=6)

print(random_floats_between_0_and_1)

[0.55722497 0.3760566  0.91621397 0.66385959 0.02912962 0.65422296]


In [18]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0

print(random_floats_between_2_and_3)

[2.55722497 2.3760566  2.91621397 2.66385959 2.02912962 2.65422296]


Operations between arrays follows the linear algebra rules.

## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22

In [22]:
feature = np.arange(6, 21)
print(feature)

label = (3 * feature) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2. 

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.

In [28]:
noise = (np.random.random(size=label.size) * 4) - 2
print(noise)

label = label + noise
print(label)

[-0.44422768  0.68005711 -0.68568798  1.74410545 -1.31767419 -0.0244966
  1.08370365 -0.24880078  1.05768828  1.93884593 -1.61310711  0.5130117
  0.27696091 -0.07288594 -1.18886584]
[21.55577232 25.68005711 27.31431202 32.74410545 32.68232581 36.9755034
 41.08370365 42.75119922 47.05768828 50.93884593 50.38689289 55.5130117
 58.27696091 60.92711406 62.81113416]
